---
- name: Configure Firewall Banners
  hosts: firewalls
  tasks:
    - name: Configure pre_login banner message
      fortinet.fortios.fortios_system_replacemsg_group:
        system_replacemsg_group:
          admin:
            -
              buffer: "WARNING: This system is monitored. Unauthorized acceess to this system is\nforbidden and will be prosecuted by law." 
              msg_type: "pre_admin-disclaimer-text"
          name: "Configure pre_login banner message"
        state: "present"
    - name: Configure post_login banner message
      fortinet.fortios.fortios_system_replacemsg_group:
        system_replacemsg_group:
          admin:
            -
              buffer: "WARNING: This system is monitored. Unauthorized acceess to this system is\nforbidden and will be prosecuted by law." 
              msg_type: "post_admin-disclaimer-text"
          name: "Configure post_login banner message"
        state: "absent"
    - name: Enable pre_login banner
      fortinet.fortios.fortios_system_global: 
        system_global:
          pre_login_banner: "enable"
