---
- name: Export switch configuration
  hosts: switches
  tasks:
  - name: Backup switch configuration 
    community.network.exos_config:
      backup: true
      backup_options:
        filename: "{{ ansible_date_time.date }}-{{ backup_name }}"
        dir_path: /home/student/backups/switches
    register: SwitchConfiguration
  - name: Save switch configuration
    copy:
      content: "{{ SwitchConfiguration.meta.raw }}"
      dest: "/home/student/backups/switches{{ ansible_date_time.date }}-{{ backup_name }}"
        

- name: Export firewall configuration
  hosts: firewalls
  tasks:
    - name: Backup firewall configuration
      fortinet.fortios.fortios_monitor:
        selector: "backup.system.config"
        params:
            scope: "global"
      register: FWConfiguration
    - name: Save firewall configuration
      copy:
        content: "{{ FWConfiguration.meta.raw }}"  
        dest: "/home/student/backups/firewalls/{{ ansible_date_time.date }}-{{ backup_name }}"
      
