---
- name: Export switch configuration
  hosts: switches
  tasks:
  - name: Backup switch configuration 
    community.network.exos_config:
      backup: true
      backup_options:
        filename: "{{ ansible_date_time.date }}"-"{{ backup_name }}""
        dir_path: /home/student/backups/switches

- name: Export firewall configuration
  hosts: firewalls
  tasks:
    - name: Backup firewall configuration
      fortios_system_config_backup_restore:
        config: "system config backup"
        filename: "/home/student/backups/firewalls/"{{ ansible_date_time.date }}"-"{{ backup_name }}""
        backup: "yes"
        scope: "global"
