---
- name: Remove switch banners
  hosts: switches
  tasks:
  - name: Remove the banner from the switch
    community.network.exos_config:
      commands:
        - unconfigure banner
      save_when: changed

- name: Remove Firewall Banners
  hosts: firewalls
  tasks:
    - name: Unconfigure pre_login banner message
      fortinet.fortios.fortios_system_replacemsg_admin:
        system_replacemsg_admin:
          buffer: "" 
          msg_type: "pre_admin-disclaimer-text"
        state: "present"
        version: "v7.0.9"
    - name: Configure post_login banner message
      fortinet.fortios.fortios_system_replacemsg_admin:
        system_replacemsg_admin:
          buffer: "" 
          msg_type: "post_admin-disclaimer-text"
        state: "present"
        version: "v7.0.9"
    - name: Disable pre_login banner
      fortinet.fortios.fortios_system_global: 
        system_global:
          pre_login_banner: "disable"
