---
- name: Remove switch banners
  hosts: switches
  tasks:
  - name: Remove the banner from the switch
    community.network.exos_config:
      commands:
        - unconfigure banner
      save_when: changed

- name: Remove Firewall Banners
  hosts: firewalls
  tasks:
    - name: Unconfigure pre_login banner message
      fortinet.fortios.fortios_system_replacemsg_group:
        system_replacemsg_group:
          admin:
            -
              buffer: "WARNING: This system is monitored. Unauthorized acceess to this system is\nforbidden and will be prosecuted by law." 
              msg_type: "pre_admin-disclaimer-text"
          name: "test1234567"
        state: "absent"
    - name: Configure post_login banner message
      fortinet.fortios.fortios_system_replacemsg_group:
        system_replacemsg_group:
          admin:
            -
              buffer: "WARNING: This system is monitored. Unauthorized acceess to this system is\nforbidden and will be prosecuted by law." 
              msg_type: "post_admin-disclaimer-text"
          name: "test123456"
        state: "absent"
    - name: Disable pre_login banner
      fortinet.fortios.fortios_system_global: 
        system_global:
          pre_login_banner: "disable"
